# Generated by Django 3.0.2 on 2020-01-21 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import feincms.contrib.richtext
import feincms.extensions.base
import feincms.module.medialibrary.fields
import feincms.module.mixins
import feincms.translations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medialibrary", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordering",
                    models.SmallIntegerField(default=0, verbose_name="ordering"),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["ordering"],
            },
            bases=(models.Model, feincms.translations.TranslatedObjectMixin),
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="is active"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is featured"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100,
                        unique_for_date="published_on",
                        verbose_name="slug",
                    ),
                ),
                (
                    "published_on",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Will be filled in automatically when entry gets published.",
                        null=True,
                        verbose_name="published on",
                    ),
                ),
                (
                    "last_changed",
                    models.DateTimeField(auto_now=True, verbose_name="last change"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("de", "German"),
                            ("zh-hans", "Chinese simplified"),
                            ("zh-hant", "Chinese traditional"),
                        ],
                        default="en",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogentries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blogentries",
                        to="elephantblog.Category",
                        verbose_name="categories",
                    ),
                ),
                (
                    "translation_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave this empty for entries in the primary language.",
                        limit_choices_to={"language": "en"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="elephantblog.Entry",
                        verbose_name="translation of",
                    ),
                ),
            ],
            options={
                "verbose_name": "entry",
                "verbose_name_plural": "entries",
                "ordering": ["-published_on"],
                "get_latest_by": "published_on",
            },
            bases=(
                models.Model,
                feincms.extensions.base.ExtensionsMixin,
                feincms.module.mixins.ContentModelMixin,
            ),
        ),
        migrations.CreateModel(
            name="RichTextContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("ordering", models.IntegerField(default=0, verbose_name="ordering")),
                (
                    "text",
                    feincms.contrib.richtext.RichTextField(
                        blank=True, verbose_name="text"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="richtextcontent_set",
                        to="elephantblog.Entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "rich text",
                "verbose_name_plural": "rich texts",
                "db_table": "elephantblog_entry_richtextcontent",
                "ordering": ["ordering"],
                "permissions": [],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaFileContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("ordering", models.IntegerField(default=0, verbose_name="ordering")),
                (
                    "type",
                    models.CharField(
                        choices=[("default", "default")],
                        default="default",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "mediafile",
                    feincms.module.medialibrary.fields.MediaFileForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="medialibrary.MediaFile",
                        verbose_name="media file",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediafilecontent_set",
                        to="elephantblog.Entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "media file",
                "verbose_name_plural": "media files",
                "db_table": "elephantblog_entry_mediafilecontent",
                "ordering": ["ordering"],
                "permissions": [],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoryTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("de", "German"),
                            ("zh-hans", "Chinese simplified"),
                            ("zh-hant", "Chinese traditional"),
                        ],
                        default="en",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="category title"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="description"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="elephantblog.Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "category translation",
                "verbose_name_plural": "category translations",
                "ordering": ["title"],
            },
        ),
    ]
